---
upload_path: "/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/test-jekyll/uploads/:year:/:month:/:day:"
body_file_url_template: "/test-jekyll/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
